apiVersion: v1
kind: Service
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-agent
  labels:
    app: mohneesh9797-puresoftware
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 1988
  selector:
    name: falcon-agent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-agent
  labels:
    app: mohneesh9797-puresoftware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-agent
    spec:
      containers:
        - name: falcon-agent
          image: registry.cn-hangzhou.aliyuncs.com/mohneesh9797-puresoftware/agent:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1988
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /mohneesh9797-puresoftware/agent/config
              name: falcon-agent-config
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /mohneesh9797-puresoftware/falcon-agent/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-agent-config
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config