apiVersion: v1
kind: Service
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-api
  labels:
    app: mohneesh9797-puresoftware
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    name: falcon-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-api
  labels:
    app: mohneesh9797-puresoftware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-api
    spec:
      containers:
        - name: falcon-api
          image: registry.cn-hangzhou.aliyuncs.com/mohneesh9797-puresoftware/api:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /mohneesh9797-puresoftware/api/config
              name: falcon-api-config
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /mohneesh9797-puresoftware/falcon-api/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-api-config
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config