apiVersion: v1
kind: Service
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-transfer
  labels:
    app: mohneesh9797-puresoftware
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6060
    - name: rpc
      port: 8433
  selector:
    name: falcon-transfer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mohneesh9797-puresoftware
  name: falcon-transfer
  labels:
    app: mohneesh9797-puresoftware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-transfer
    spec:
      containers:
        - name: falcon-transfer
          image: registry.cn-hangzhou.aliyuncs.com/mohneesh9797-puresoftware/transfer:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6060
              name: http
              protocol: TCP
            - containerPort: 8433
              name: rpc
              protocol: TCP
          volumeMounts:
            - mountPath: /mohneesh9797-puresoftware/transfer/config
              name: falcon-transfer-config
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /mohneesh9797-puresoftware/falcon-transfer/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-transfer-config
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config